Parser werkt volledig zonder exceptions.
operator >> werkt niet "cause TinyXML".

network.startSimulation doet de compilatie failen:
"undefined reference to `Network::fgkMaxTicks'"